"""Add free images cilumn

Revision ID: 29564326672c
Revises: c677b1c56587
Create Date: 2024-05-31 16:00:01.376293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29564326672c'
down_revision: Union[str, None] = 'c677b1c56587'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('free_images_left', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'free_images_left')
    # ### end Alembic commands ###
