"""Remove subscription info

Revision ID: 469cb30441b2
Revises: 29564326672c
Create Date: 2024-09-18 17:01:15.738611

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '469cb30441b2'
down_revision: Union[str, None] = '29564326672c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'has_active_subscription')
    op.drop_column('users', 'subscription_end_date')
    op.drop_column('users', 'free_images_left')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('free_images_left', sa.INTEGER(), nullable=True))
    op.add_column('users', sa.Column('subscription_end_date', sa.DATETIME(), nullable=True))
    op.add_column('users', sa.Column('has_active_subscription', sa.BOOLEAN(), nullable=True))
    # ### end Alembic commands ###
